
# ç”Ÿæˆæ—¶é—´: 2025-11-12 03:08:05
# èŠ‚ç‚¹æ•°é‡: 17
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: vmess_node
  type: vmess
  server: 2001:bc8:32d7:302::10
  port: '44579'
  uuid: 8e34e170-13ae-4892-9d20-05962acc9f84
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
  servername: ''
- name: vmess_node
  type: vmess
  server: 2001:bc8:1203:209::50
  port: '23008'
  uuid: e994b804-345c-4e8b-a827-7e005694d146
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /github.com/Alvin9999
    headers:
      Host: www.bing.com
  servername: ''
- name: vmess_node
  type: vmess
  server: 47.245.106.193
  port: '22433'
  uuid: bfcb103f-2133-4965-8684-6b4c8ef7a774
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 141.101.121.26
  port: '80'
  uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /?BIA_TELEGRAM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)
    headers:
      Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
  servername: ''
- name: vmess_node
  type: vmess
  server: 103.243.26.209
  port: '10086'
  uuid: c5ec2e3f-c058-46a8-a148-1831824bb94b
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 103.243.26.209
  port: '8080'
  uuid: bc7e6840-ab83-4570-eaae-d9aff1e2da09
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 208.76.223.218
  port: '27092'
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 43.247.134.213
  port: '59516'
  uuid: 2906e19e-c99f-456e-bcb3-c5472fd594e5
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 62.113.200.175
  port: '44749'
  uuid: ba1d9a12-7fb5-495e-a547-c87264db41ea
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 62.113.200.175
  port: '46668'
  uuid: 680f3f4d-a13a-4869-ada6-894683cf2ffe
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 152.70.92.69
  port: '80'
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 1.32.216.163
  port: '27578'
  uuid: 3b3aff88-2ed2-4c68-bc0f-d1efe4131e2c
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: 175.29.22.101
  port: '28034'
  uuid: d2540325-9ad6-33d7-be86-259b5bba4ef8
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ''
- name: vmess_node
  type: vmess
  server: v9.heduian.link
  port: '30809'
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
  servername: ''
- name: vmess_node
  type: vmess
  server: nl-v2ray.freevmess.com
  port: '2083'
  uuid: c3d066bc-4170-4006-a95c-0012367e8f13
  alterId: '0'
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: nl-v2ray.freevmess.com
- name: vmess_node
  type: vmess
  server: 141.101.120.130
  port: 80
  uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /?---@AZARBAYKAB1---@AZARBAYJAB1---@AZARBAYJAB1---@AZARBAYJAB1---@AZARBAYJAB1/?ed=2560
    headers:
      Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
- name: vmess_node
  type: vmess
  server: 8.217.92.110
  port: 20522
  uuid: 31e1f90f-0218-4097-91f9-a42df9b3334a
  alterId: '0'
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: /telegram_@sswia
    headers:
      Host: ''
proxy-groups:
- name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - vmess_node
  - DIRECT
- name: ğŸ¯ å…¨çƒç›´è¿
  type: select
  proxies:
  - DIRECT
- name: ğŸŒ å›½å¤–åª’ä½“
  type: select
  proxies:
  - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - DIRECT
- name: ğŸ“¢ ç”µæŠ¥æ¶ˆæ¯
  type: select
  proxies:
  - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - DIRECT
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  type: select
  proxies:
  - DIRECT
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  type: select
  proxies:
  - DIRECT
- name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  type: select
  proxies:
  - DIRECT
- name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
  type: select
  proxies:
  - DIRECT
- name: ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
  type: select
  proxies:
  - DIRECT
- name: ğŸ® æ¸¸æˆåŠ é€Ÿ
  type: select
  proxies:
  - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - DIRECT
- name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  type: select
  proxies:
  - REJECT
rules:
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/RuleSet/AdBlock/LocalAdBlock.list,ğŸ›‘
  å¹¿å‘Šæ‹¦æˆª
- DOMAIN,clash.razord.top,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
- DOMAIN-SUFFIX,google.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,googleapis.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,gmail.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,youtube.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,facebook.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,twitter.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,instagram.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,telegram.org,ğŸ“¢ ç”µæŠ¥æ¶ˆæ¯
- DOMAIN-SUFFIX,github.com,ğŸŒ å›½å¤–åª’ä½“
- DOMAIN-SUFFIX,githubusercontent.com,ğŸŒ å›½å¤–åª’ä½“
- GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
- MATCH,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
